### ISSUE TITLE
Optional field support

### ISSUE THREAD

**Issue by RoRoche** [kboyarshinov/ActivityScreens#6]
Is it possible to add the "required/optional" status of a field?
So that it's removed from the builder constructor and can be configured via a specific setter method?
The check would be removed from the `checkArguments` method and replaced by a simple `if(bundle.containsKey("optional_field_key")` in the inject method before setting the field for example.

**Comment by kboyarshinov** [comment]
It is already supported. 
`@ActivityArg(required = false)`
